// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tweedieDensity
arma::vec tweedieDensity(arma::vec x, arma::vec mean, arma::vec dispersion, arma::vec power, bool log);
RcppExport SEXP _tweedieDistr_tweedieDensity(SEXP xSEXP, SEXP meanSEXP, SEXP dispersionSEXP, SEXP powerSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type power(powerSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(tweedieDensity(x, mean, dispersion, power, log));
    return rcpp_result_gen;
END_RCPP
}
// tweedieCDF
arma::vec tweedieCDF(arma::vec x, arma::vec mean, arma::vec dispersion, arma::vec power);
RcppExport SEXP _tweedieDistr_tweedieCDF(SEXP xSEXP, SEXP meanSEXP, SEXP dispersionSEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(tweedieCDF(x, mean, dispersion, power));
    return rcpp_result_gen;
END_RCPP
}
// tweedieInvCDF
arma::vec tweedieInvCDF(arma::vec q, arma::vec mean, arma::vec dispersion, arma::vec power);
RcppExport SEXP _tweedieDistr_tweedieInvCDF(SEXP qSEXP, SEXP meanSEXP, SEXP dispersionSEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(tweedieInvCDF(q, mean, dispersion, power));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tweedieDistr_tweedieDensity", (DL_FUNC) &_tweedieDistr_tweedieDensity, 5},
    {"_tweedieDistr_tweedieCDF", (DL_FUNC) &_tweedieDistr_tweedieCDF, 4},
    {"_tweedieDistr_tweedieInvCDF", (DL_FUNC) &_tweedieDistr_tweedieInvCDF, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_tweedieDistr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
