# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tweedieDensity <- function(x, mean, dispersion, power, log) {
    .Call(`_tweedieDistr_tweedieDensity`, x, mean, dispersion, power, log)
}

tweedieCDF <- function(x, mean, dispersion, power) {
    .Call(`_tweedieDistr_tweedieCDF`, x, mean, dispersion, power)
}

tweedieInvCDF <- function(q, mean, dispersion, power) {
    .Call(`_tweedieDistr_tweedieInvCDF`, q, mean, dispersion, power)
}

